config/routes.rb
Reclamoes::Application.routes.draw do
  
  match "/auth/facebook/callback" => "sessions#create"
  get "sessions/destroy"

  resources :reclamacaos

  root :to => "reclamacaos#index"

   match ':controller(/:action(/:id(.:format)))'
  
>>>>>>> 38f3a1b1f8eb6700b72f5b4e849fe25a96d075c7:config/routes.rb
end

app/models/reclamacao.rb
class Reclamacao < ActiveRecord::Base

  validates_presence_of :titulo, :descricao, :tipo, :empresa, :usuario_id
end

app/models/tweet.rb
class Tweet
  
  attr_reader :user, :description, :date
  
  public
  def self.cria_tweets(results)
    return results unless results.size > 0
    tweets = []
    results.each do |hash|
      tweets << Tweet.new(hash[:from_user], hash[:text], hash[:created_at])
    end
    tweets
  end
  
  private
  def initialize(user, description, date) 
    @user = user
    @description = description
    @date = date
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reclamacaos_controller.rb
class ReclamacaosController < ApplicationController
  # GET /reclamacaos
  # GET /reclamacaos.xml
  def index
    @reclamacaos = Reclamacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reclamacaos }
    end
  end

  # GET /reclamacaos/1
  # GET /reclamacaos/1.xml
  def show
    @reclamacao = Reclamacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reclamacao }
    end
  end

  # GET /reclamacaos/new
  # GET /reclamacaos/new.xml
  def new
    @reclamacao = Reclamacao.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reclamacao }
    end
  end

  # GET /reclamacaos/1/edit
  def edit
    @reclamacao = Reclamacao.find(params[:id])
  end

  # POST /reclamacaos
  # POST /reclamacaos.xml
  def create
    @reclamacao = Reclamacao.new(params[:reclamacao])

    respond_to do |format|
      if @reclamacao.save
        format.html { redirect_to(@reclamacao, :notice => 'Reclamacao was successfully created.') }
        format.xml  { render :xml => @reclamacao, :status => :created, :location => @reclamacao }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reclamacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reclamacaos/1
  # PUT /reclamacaos/1.xml
  def update
    @reclamacao = Reclamacao.find(params[:id])

    respond_to do |format|
      if @reclamacao.update_attributes(params[:reclamacao])
        format.html { redirect_to(@reclamacao, :notice => 'Reclamacao was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reclamacao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reclamacaos/1
  # DELETE /reclamacaos/1.xml
  def destroy
    @reclamacao = Reclamacao.find(params[:id])
    @reclamacao.destroy

    respond_to do |format|
      format.html { redirect_to(reclamacaos_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:uid] = auth()[:uid]
  end

  def destroy
  end
  
  def auth
    request.env["omniauth.auth"]
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
require 'rubygems'
require 'twitter'
require 'tweet'

module ApplicationHelper

	def tweets(hash_tag="reclamoes")
		search = Twitter::Search.new
		result = search.hashtag(hash_tag)
		array = result.to_a
		puts array.inspect
		tweets = Tweet.cria_tweets(array) 

		return tweets
	end

  
end

app/helpers/reclamacaos_helper.rb
module ReclamacaosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gamers Reclam&otilde;es</title>
  <meta name="robots" content="noindex nofollow" />
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>

<body>

<%= yield %>

</body>
</html>

app/views/reclamacaos/_form.html.erb
<%= form_for(@reclamacao) do |f| %>
  <% if @reclamacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reclamacao.errors.count, "error") %> prohibited this reclamacao from being saved:</h2>

      <ul>
      <% @reclamacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br />
    <%= f.text_field :usuario_id %>
  </div>
  <div class="field">
    <%= f.label :empresa %><br />
    <%= f.text_field :empresa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reclamacaos/edit.html.erb
<h1>Editing reclamacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @reclamacao %> |
<%= link_to 'Back', reclamacaos_path %>

app/views/reclamacaos/index.html.erb
<div class="container">

<div id="header">

    <h1>Logo dos Reclamoes</h1>

    <ul class="menu-principal">
      <li><a href="#" title="Top 10 Reclamações">Top 10</a></li>
      <li><a href="#" title="Categorias de reclamações">Reclamações</a></li>
      <li><a href="#" title="Sobre">Sobre</a>
      <li><a href="#" title="Contato">Contato</a>
    </ul><!-- .menu-principal -->

</div><!-- #header -->

  <form>
    <p>Aqui entra um botao para abrir o form de cadastro de reclamacao</p>
  </form>
  
  <ul class="reclamacoes">
  
    <% @reclamacaos.each do |reclamacao| %>
      <li>
        <h2><%= reclamacao.titulo %></h2>
        <p><%= reclamacao.tipo %> - <%= reclamacao.empresa %></p>
        <p class="descricao"><%= reclamacao.descricao %></p><!-- .descricao -->
        <p class="votar">Botao de votar</p><!-- .votar -->
        <p class="autor">Autor: <%= reclamacao.usuario_id %></p><!-- .autor --> 
        
        <p><%= link_to 'Show', reclamacao %> - <%= link_to 'Edit', edit_reclamacao_path(reclamacao) %> - <%= link_to 'Destroy', reclamacao, :confirm => 'Are you sure?', :method => :delete %></p>
      </li>
    <% end %>
    
  </ul><!-- .reclamacoes -->

  <br />

  <%= link_to 'New Reclamacao', new_reclamacao_path %>

</div><!-- .container -->

app/views/reclamacaos/new.html.erb
<h1>New reclamacao</h1>

<%= render 'form' %>

<%= link_to 'Back', reclamacaos_path %>

app/views/reclamacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @reclamacao.titulo %>
</p>

<p>
  <b>Descricao:</b>
  <%= @reclamacao.descricao %>
</p>

<p>
  <b>Tipo:</b>
  <%= @reclamacao.tipo %>
</p>

<p>
  <b>Usuario:</b>
  <%= @reclamacao.usuario_id %>
</p>

<p>
  <b>Empresa:</b>
  <%= @reclamacao.empresa %>
</p>


<%= link_to 'Edit', edit_reclamacao_path(@reclamacao) %> |
<%= link_to 'Back', reclamacaos_path %>

app/views/tweets/index.html.erb
<table>
	<tr>
		<th>User</th>
		<th>Description</th>
		<th>Date</th>				
	</tr>
<% tweets.each do |t| %>
	<tr>
		<td><%= t.user %></td>
		<td><%= t.description %></td>
		<td><%= t.date %></td>				
	</tr>
<% end %>

<table>